version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - D:\windows_user_files\Desktop\workus\2024 Junior Python Developer Global Mind Associated\database_folder:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


  app:
    build: .
    command: python main.py
    volumes:
      - ./application:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

